# Generated by Django 5.1.3 on 2024-11-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_budgetentry_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetentry',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budgetentry',
            name='recurring_frequency',
            field=models.CharField(choices=[('NONE', 'None'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='NONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='budgetentry',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
